public: false
# If true, then exercise kernels synced to kaggle will have internet enabled and will begin
# with a cell that pip installs the current learntools branch. (Useful for testing 
# notebooks on Kernels without requiring image docker deploy for every learntools change)
development: true
# By itself, this flag does nothing. But it can be useful to have 'testing' cells in exercise
# notebooks (testing the checking code on various correct and incorrect solutions) whose 
# inclusion in the rendered notebook is conditioned on this flag (using a macro like #%%RM_IF(PROD)%%
# where "prod" is the opposite of "testing")
testing: false
